server.port=${PORT:10000}
server.address=0.0.0.0

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/bingo_db?sslmode=disable}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1027}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.data.jpa.repositories.bootstrap-mode=lazy
spring.main.lazy-initialization=true
spring.sql.init.mode=never

spring.flyway.enabled=false

cors.allowed.origins=${CORS_ALLOWED_ORIGINS:*}

jwt.secret=${JWT_SECRET:c3VhLWNoYXZlLXN1cGVyLXNlY3JldGEtY29tLXBlaG8tbWVub3MtMzItY2FyYWN0ZXJlcw==}
jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.org.springframework=INFO
logging.level.com.empresa.bingo=INFO

app.name=Bingo Application
app.version=1.0.0